<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>

  <PropertyGroup>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Authors>Jiri Cepelka</Authors>
    <Company>Software9119</Company>
    <Description>Provides list with fast enumerator. It enumerates circa 30 % faster then List&lt;T&gt; enumerator.</Description>
    <Copyright>Verbal consent needed.</Copyright>    
    <AssemblyName>Software9119.FastEnumerationList</AssemblyName>
    <RootNamespace>$(AssemblyName)</RootNamespace>
    <Version>4.0.1</Version>
    <AssemblyVersion>4.0.1.0</AssemblyVersion>
    <UserSecretsId>aa92bd68-ea6c-4e98-a6fb-c1c2d65ed617</UserSecretsId>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>
    <PackageId>$(AssemblyName).$(Configuration)</PackageId>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <PackageId>$(AssemblyName)</PackageId>
  </PropertyGroup>

  <Target Name="CopyPackage" AfterTargets="Pack">
    <Copy SourceFiles="$(OutputPath)..\$(PackageId).$(PackageVersion).nupkg" DestinationFolder=".\..\packages\" />
  </Target>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="6.0.1" />
  </ItemGroup>
</Project>
